[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sondre Lefsaker <sondre.lefsaker@itera.no>"]

[profile.dev]
opt-level = 2

[dev-dependencies]
hamcrest = "0.1"

[dependencies]
bmp = "0.2"
rand = "0.3"
rayon= "0.6"
